In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


# Introduction to Tensors
## Creating Tensors

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar



tensor(7)

In [6]:
scalar.ndim

0

In [7]:
#Convert tensor back to python int
scalar.item()

7

In [8]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# Matrix
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
matrix.ndim

2

In [13]:
matrix.shape

torch.Size([2, 2])

In [14]:
#Tensor
tensor = torch.tensor([[[1,2,3],
                        [2,3,4],
                        [3,4,5]]])

In [15]:
tensor

tensor([[[1, 2, 3],
         [2, 3, 4],
         [3, 4, 5]]])

In [16]:
tensor.ndim

3

In [17]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
# Scalars and vectors are lower case,
#Matrix and tensor are uppercase

# Random Tensors

In [19]:
# Create a random tensors of size (3,4)

random_tensor = torch.rand(3,4)

In [20]:
random_tensor

tensor([[0.9050, 0.0937, 0.4125, 0.6011],
        [0.7416, 0.6334, 0.5647, 0.0525],
        [0.1014, 0.5442, 0.6344, 0.5716]])

In [21]:
random_tensor.ndim

2

In [22]:
random_tensor.shape

torch.Size([3, 4])

In [23]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #Height, width, color(rgb)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and Ones

In [25]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
ones.dtype

torch.float32

# Creating a rannge of tensors

In [32]:
# Use torch.range()

temp1 = torch.arange(0,10)
temp1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
temp2 = torch.arange(start=0, end=200, step=45)
temp2

tensor([  0,  45,  90, 135, 180])

# Creating a tensor like

In [35]:
ten_zeros = torch.zeros_like(input=temp1)

In [36]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
ten_ones = torch.ones_like(temp1)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# Tensor Datatypes

In [39]:
f32 = torch.tensor([3.0, 6.0, 9.0], dtype=None)
f32

tensor([3., 6., 9.])

In [40]:
f32.dtype

torch.float32

In [41]:
f16 = torch.tensor([1,2,3], dtype=torch.float16)
f16

tensor([1., 2., 3.], dtype=torch.float16)

In [42]:
f32 = torch.tensor([3.0, 6.0, 9.0],
                   dtype=None,
                   device=None,
                   requires_grad=False)
f32

tensor([3., 6., 9.])

In [44]:
f16 = f32.type(torch.float16)
f16

tensor([3., 6., 9.], dtype=torch.float16)

In [45]:
f16 * f32

tensor([ 9., 36., 81.])

In [46]:
i32 = torch.tensor([3,6,9], dtype=torch.int32)
i32

tensor([3, 6, 9], dtype=torch.int32)

In [47]:
i32*f16

tensor([ 9., 36., 81.], dtype=torch.float16)

# Getting information from tensors
1. check datatype, tensor.dtype
2. check shape, tensor.shape
3. check device, tensor.device

In [56]:
r = torch.rand([3,4], dtype=torch.float)
r

tensor([[0.3777, 0.0469, 0.4772, 0.9368],
        [0.3275, 0.8409, 0.2425, 0.0780],
        [0.6662, 0.6539, 0.3181, 0.3329]])

In [53]:
# print(r)
print(f"Data Type {r.dtype}")
print(f"Shape {r.shape}")
print(f"Device {r.device}")

Data Type torch.float32
Shape torch.Size([3, 4])
Device cpu


# Manipulating Tensor (Tensor Operations)

Operations Include:
1. Addition
2. Subtraction
3. Multiplication (Element Wise)
4. Division
5. Matrix Multiplication

In [58]:
# Create  Tensor
tensor = torch.tensor([1,2,3])
#add
tensor + 100

tensor([101, 102, 103])

In [60]:
#element wise multiplication
tensor * 13

tensor([13, 26, 39])

In [61]:
#Subtraction
tensor-10

tensor([-9, -8, -7])

In [62]:
#Division
tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [63]:
#pytorch inbuilt functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [64]:
torch.add(tensor,8)

tensor([ 9, 10, 11])

# Matrix Multiplication

Two rules for mat mul : inner dimensions must match (3,4) @ (4,3) -> (3,3)

matrixmultiplication.xyz


In [69]:
a = torch.rand((3,4))
b = torch.rand((4,3))

c = a @ b

In [70]:
c

tensor([[1.7566, 0.8895, 0.7317],
        [0.5357, 0.3532, 0.3866],
        [0.8970, 0.3907, 0.3072]])

In [71]:
c2 = torch.matmul(a, b)

In [72]:
c2

tensor([[1.7566, 0.8895, 0.7317],
        [0.5357, 0.3532, 0.3866],
        [0.8970, 0.3907, 0.3072]])

In [81]:
%%time
# Matrix multiplication of two vectors
a = torch.arange(1,5)
b = torch.arange(1,5)

torch.matmul(a,b)

a.ndim

CPU times: user 1.45 ms, sys: 0 ns, total: 1.45 ms
Wall time: 3.54 ms


1

In [78]:
a.shape

torch.Size([4])

In [80]:
a.size()

torch.Size([4])

In [2]:
# One of the most common errors
import torch
tensorA = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensorB = torch.tensor([[7,10],
                        [7,3],
                        [5,12]])

In [8]:
tensorA.shape, tensorB.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [5]:
tensorA.ndim

2

In [ ]:
# tensorC = torch.matmul(tensorA, tensorB)



In [14]:
tensorB.T

tensor([[ 7,  7,  5],
        [10,  3, 12]])

In [12]:
tensorA.shape, tensorB.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [13]:
tensorA @ tensorB.T

tensor([[27, 13, 29],
        [61, 33, 63],
        [95, 53, 97]])

# Finding min, max, mean, sum, etc (tensor aggregation)

In [20]:
# Create a tensor

x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [17]:
#Find the min
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [18]:
x.max(), torch.max(x)

(tensor(90), tensor(90))

In [19]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [22]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [23]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [26]:
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [28]:
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

# Reshaping the Tensor

## Reshaping, stacking, squeezing and unsqueezing

* Reshaping - reshapes an input tensor to a defined shape
* View - Returns a view of an input tensor of certain shape but keep the same memory as the original
* Stacking - combine multiple tensors on top of each other
* Squeeze - Removes all '1' dimensions from tensors
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted in certain way

In [31]:
import torch

x = torch.arange(1.,10)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [32]:
x.reshape(1,9)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [34]:
x.reshape(9,1).ndim

2

In [35]:
x.ndim

1

In [36]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [37]:
# z and x share same memory,
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [39]:
z[0,2] = 99

In [40]:
x

tensor([ 5.,  2., 99.,  4.,  5.,  6.,  7.,  8.,  9.])

In [41]:
z

tensor([[ 5.,  2., 99.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [48]:
# Stack tensors on top of each other

newx = torch.stack((x,x,x,x), dim=1)

In [49]:
newx

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [99., 99., 99., 99.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.]])

In [ ]:
torch.hstack()

In [50]:
newx = torch.hstack((x,x,x,x))
newx

tensor([ 5.,  2., 99.,  4.,  5.,  6.,  7.,  8.,  9.,  5.,  2., 99.,  4.,  5.,
         6.,  7.,  8.,  9.,  5.,  2., 99.,  4.,  5.,  6.,  7.,  8.,  9.,  5.,
         2., 99.,  4.,  5.,  6.,  7.,  8.,  9.])

In [51]:
newx = torch.vstack((x,x,x,x))
newx

tensor([[ 5.,  2., 99.,  4.,  5.,  6.,  7.,  8.,  9.],
        [ 5.,  2., 99.,  4.,  5.,  6.,  7.,  8.,  9.],
        [ 5.,  2., 99.,  4.,  5.,  6.,  7.,  8.,  9.],
        [ 5.,  2., 99.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [62]:

a = torch.rand((10))
a

tensor([0.8338, 0.9925, 0.4413, 0.2187, 0.8923, 0.5532, 0.8243, 0.4680, 0.2123,
        0.4692])

In [75]:
a2 = torch.unsqueeze(a,1)

In [76]:
a.shape, a2.shape

(torch.Size([10]), torch.Size([10, 1]))

In [80]:
torch.squeeze(a2,1)

tensor([0.8338, 0.9925, 0.4413, 0.2187, 0.8923, 0.5532, 0.8243, 0.4680, 0.2123,
        0.4692])

In [87]:
# torch.permute
#This is a view, therefore shares the original shape

xori = torch.rand((225,225,3))
xori.shape

torch.Size([225, 225, 3])

In [84]:
xnew = torch.permute(xori, (2,0,1))

In [85]:
xnew.shape

torch.Size([3, 225, 225])

# Indexes in Tensors

In [88]:
#Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)

In [90]:
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [91]:
x[:,:,1]

tensor([[2, 5, 8]])

In [92]:
x[:,1,1]

tensor([5])

In [93]:
x[0,0,:]

tensor([1, 2, 3])

In [94]:
#Index for 9
x[0,2,2]

tensor(9)

In [95]:
#Index for 3 to 9
x[0,:,2]

tensor([3, 6, 9])

# Pytorch tensors and numpy

From Numpy to Tensor

torch.from_numpy()


From pytorch tensor to numpy


torch.Tensor.numpy()


In [96]:
# Numpy array to tensor
import torch
import numpy as np


array = np.arange(1., 8)


In [100]:
array.dtype

dtype('float64')

In [98]:
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [102]:
x2 = torch.Tensor.numpy(tensor)

In [106]:
type(x2), x2.dtype

(numpy.ndarray, dtype('float64'))

# Reproducibility

In [128]:
import torch

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

In [137]:
torch.manual_seed(RANDOM_SEED)
a = torch.rand(3,3)
torch.manual_seed(RANDOM_SEED)
b = torch.rand(3,3)
print(a)
print(b)
print(a==b)


tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


# Accessing GPU in Pytorch

In [1]:
## Getting a GPU
!nvidia-smi

Thu Jun  5 18:39:34 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   41C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
# Check for GPU access with pytorch
import torch
torch.cuda.is_available()

True

In [3]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device


'cuda'

In [4]:
# Count number of devices
torch.cuda.device_count()

1

In [8]:
# Putting tensors and models on the GPU
a = torch.tensor([1,2,3])
print(a, a.device)

tensor([1, 2, 3]) cpu


In [14]:
# Move tensor to gpu if available
ag = a.to(device)

In [15]:
ag.device

device(type='cuda', index=0)

In [17]:
ac = ag.to(device='cpu')

In [18]:
ac

tensor([1, 2, 3])

In [21]:
ac.numpy()

array([1, 2, 3])